// Generates the lib/config.ts file with a BUILD_ID constant
// based on the current timestamp. This can be used to force
// cache invalidation in the client when a new build is deployed.

import fs from "fs";
import path from "path";

const buildId = Date.now().toString();
const content = `// This file is auto-generated by scripts/buildConfig.ts
export const BUILD_ID = '${buildId}';
`;

const outputPath = path.join(__dirname, "..", "lib", "config.ts");

fs.writeFileSync(outputPath, content, "utf8");
